### ISSUE TITLE
除了第一个输出是正确的后面的输出全是一样的

### ISSUE THREAD

**Issue by RiuHDuo** [onlynight/exchange#3]
输出全是一样的

```
<?xml version="1.0" encoding="UTF-8"?>
<resources>
    <string name="completed">Installed to complete</string>
    <string name="unable_to_choose_situation">Installed to complete</string>
    <string name="unable_to_choose_situation_tip">Installed to complete</string>
    <string name="unable_to_choose_situation_tip_2">Installed to complete</string>
</resources>
```

**Comment by dyzs** [comment]
我也是这样的，有解决吗请问

**Comment by zhubinsheng** [comment]
他这个方法中的：
int index = 0; 一直都是0没有写自增长，所以获取的值一直都是第一个

@Override
    public void writeNewDocument(TranslatorDocument<Document> document, String targetLanguage) {
        Document doc = document.getSourceDocument();
        Element rootElement = doc.getRootElement();
        Iterator iterator = rootElement.elementIterator();
        int index = 0;
        StringBuilder sb = new StringBuilder();
        while (iterator.hasNext() && document.getDestStrings() != null) {
            Element element = (Element) iterator.next();
            element.setText(document.getDestStrings().get(index));
        }
        sb.append(doc.asXML());
        writeNewDocument(document.getPath(), sb, targetLanguage);
    }

**Comment by onlynight** [comment]
已经修复了，兄弟，谢谢。
